### ISSUE TITLE
genome_subtract (X-Y) also simplifies X?

### ISSUE THREAD

**Issue by gaiusjaugustus** [const-ae/tidygenomics#2]
I had chromosome 1 which looked like this, (X):
![image](https://cloud.githubusercontent.com/assets/10555763/25917015/8f44cdec-357b-11e7-9c65-c9cf91941aa7.png)

And what I wanted to subtract (Y):
![image](https://cloud.githubusercontent.com/assets/10555763/25917078/cb578cc0-357b-11e7-9bed-1241fccdd4a9.png)

I had hoped that it would **just** subtract Y from X (i.e., I am just trying to remove centromeric data) , but here is the output after running:
`genome_subtract(X, Y, by=c("chromosome","start","end"))`

![image](https://cloud.githubusercontent.com/assets/10555763/25917187/09b2d754-357c-11e7-97cf-f8f3c09de920.png)

I assume this is by design, but I think it would be a good option to allow only those reads/segments/ranges that overlap ranges in Y to be affected, and not to have ranges in X affect other ranges in X.

Thoughts?  Did I do something wrong or misinterpret?

Thanks,
Gaius

**Comment by const-ae** [comment]
Hi, 
thank you for making such a detailed bug report. This was not a design decision, but an edge case that slipped through my unit tests. 
I think, I fixed the issue could you try to install the latest version from github and test it yourself?

**Comment by gaiusjaugustus** [comment]
Reinstalled tidygenomics and reran the same script.  Output looks as I would expect now. 

For completeness, the final output is:
![image](https://cloud.githubusercontent.com/assets/10555763/25963718/2d5119b2-3637-11e7-8153-2cac3c2c0d66.png)

Thank you for a great package and quick followup!
