### ISSUE TITLE
Feature Request: Join nearby

### ISSUE THREAD

**Issue by gaiusjaugustus** [const-ae/tidygenomics#3]
Hi,
I'm working on this now, but it may be a while.  The idea is that if you want to join ranges that are close to each other, but up to a threshold.  This threshold could be a distance (e.g. join any ranges within 1MB of each other), or could be a ratio of the total length of the two ranges + the gap.

Currently, my understanding is that tidygenomics only has join_closest which joins two ranges that are closest together regardless of what that distance is.

Here's an illustration of what I'm proposing.

![joinnearby](https://cloud.githubusercontent.com/assets/10555763/26650373/09eeedce-45fe-11e7-9076-b43193429a77.jpg)

The idea of the ratio option is based on an addon script from PennCNV.  If I figure this out, maybe I'll try a pull request.  Never done that before, but willing to try.

**Comment by const-ae** [comment]
Hi Gaius,

thank you for your interest in the package. 
I am not quite sure if I correctly understood your proposal, the `genome_join_closest` function actually already supports a gap parameter (called `max_distance`). This is the best way forward if you have 2 lists. For example you want to join a list of genes with a list of promoters, but only if they are closer than 1kb.

If you want to merge elements from the same dataset if they are close, you can use the `genome_cluster` function, which gives elements that are close to each other the same `cluster_id`, so they can subsequently be combined with the normal dplyr `group_by(cluster_id) %>% summarize(...)` pattern.

If you would still be interested in making a pull request adding the ratio threshold, I would be happy to accept it. Here are the places where I implemented the logic for [`genome_cluster`](https://github.com/Artjom-Metro/tidygenomics/blob/master/src/cluster_interval.cpp#L107) and for [`genome_join_closest`](https://github.com/Artjom-Metro/tidygenomics/blob/master/R/join_closest.R#L69).

Best, Constantin

**Comment by gaiusjaugustus** [comment]
Thanks for your help.  I was hoping that you'd already have some idea of a way to do this.  I've tried your solution, and it works well for a distance threshold.  However, I'm having issues implementing the ratio threshold.  This ratio threshold pretty much indicates that if the gap between the two ranges is smaller than some threshold (%) of the combined size, join those regions.

For my research, I often need a more dynamic threshold to determine if genomic ranges should be combined.  I'll close this for now, and if I need to do a pull request, I will.  Thanks again.
